use_frameworks!

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
# source ‘https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git’

target 'CXDevAssistiveTool_Example' do
  pod 'CXDevAssistiveTool', :path => '../'

  target 'CXDevAssistiveTool_Tests' do
    inherit! :search_paths

    
  end
end

#关闭引用第三方库的bitcode
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
        end
    end
end

pod 'SDWebImage', '4.4.6'
pod 'CXNetworking', :git=>'git@github.com:shenchunxing/CXNetworking.git'
pod 'CXLogger', :git=>'git@github.com:shenchunxing/CXLogger.git'

